### PR TITLE
Fix enforce unique tasks

### LINKED ISSUE #211: Fix task list indexing issue
In the `toString` method of `TaskList`, it doesn't handle duplicate tasks well.

image

### PR DESCRIPTION
**Pull request by Ramanathan0908**
Fixes #211

### CODE REVIEW

File: src/main/java/seedu/uninurse/logic/commands/AddTaskCommand.java [hunk 1]
```diff
@@ -56,6 +56,11 @@ public CommandResult execute(Model model) throws CommandException {
 
         Patient personToEdit = lastShownList.get(index.getZeroBased());
 
+
+        if (personToEdit.getTasks().hasTask(task)) {
+            throw new CommandException(Messages.MESSAGE_DUPLICATE_TASK);
+        }
```
Comment (izzahaj) [inline src/main/java/seedu/uninurse/logic/commands/AddTaskCommand.java:62]: In `MedicationList` and `ConditionList`, duplicates are handled by catching `DuplicateXXException` thrown by the `XXList#add()` method. Your way seems to be a cleaner way to handle it. Would like @BlopApple's input since it involves the features his features as well.

File: src/main/java/seedu/uninurse/commons/core/Messages.java [hunk 2]
```diff
@@ -11,4 +11,6 @@ public class Messages {
     public static final String MESSAGE_INVALID_TASK_INDEX = "The task index provided is invalid";
     public static final String MESSAGE_PERSONS_LISTED_OVERVIEW = "%1$d persons listed!";
 
+    public static final String MESSAGE_DUPLICATE_TASK = "This task already exists for this patient";
```
Comment (izzahaj) [inline src/main/java/seedu/uninurse/commons/core/Messages.java:14]: Perhaps it may be better to standardise where the messages are placed, and what exactly the message is. In `MedicationList` and `ConditionList`, the message for duplicate values is placed in the respective `AddXXCommand` class, and we've standardised the error message to include other details. Do take a look at those classes for reference since they're all quite similar.

File: src/main/java/seedu/uninurse/logic/commands/AddTaskCommand.java (hunk 1 above)
Comment (BlopApple) [reply src/main/java/seedu/uninurse/logic/commands/AddTaskCommand.java:62]: I'm fine with either way as long as we standardize the way we handle duplicates by letting `GenericList<T>` to handle it or by letting the `Command` to handle it. 
Will merge this PR for now and request changes in a separate issue.

File: src/main/java/seedu/uninurse/commons/core/Messages.java (hunk 2 above)
Comment (BlopApple) [reply src/main/java/seedu/uninurse/commons/core/Messages.java:14]: Similar as above.

**Review by BlopApple — APPROVED** [review]
