### PR TITLE
Fix instances of patient modification in commands

### LINKED ISSUE #233: Update all instances of Patient modification in commands
The current method of creating a new immutable `Patient` after every command relating to it involves using the `Patient` constructor with a long list of attributes. A cleaner method to create a new immutable `Patient` can be used for ease of future implementations and code clarity.

### PR DESCRIPTION
**Pull request by BlopApple**
Closes #233, #237
This PR fixes patient modification by creating new overloaded constructors that returns a new immutable patient with the specified updated list (e.g. `ConditionList` or `TaskLIst`).

Inconsistencies in `EditTaskCommand` and `DeleteTaskCommand` are also addressed.

### CODE REVIEW

File: src/main/java/seedu/uninurse/model/person/Patient.java [hunk 1]
```diff
@@ -30,6 +30,28 @@ public Patient(Name name, Phone phone, Email email, Address address, ConditionLi
         this.tasks = tasks;
     }
 
+    /**
+     * Used to return a new immutable {@code Patient} when {@code ConditionList} is updated.
+     * @param patient the patient to be updated
+     * @param condupdatedConditionsitions the updated conditions.
```
Comment (izzahaj) [inline src/main/java/seedu/uninurse/model/person/Patient.java:36]: There is a typo here
```suggestion
     * @param updatedConditions the updated conditions.
```

**Review by izzahaj — CHANGES_REQUESTED** [review]
Minor typo in one of the JavaDoc comments; otherwise, LGTM.

File: src/main/java/seedu/uninurse/model/person/Patient.java (hunk 1 above)
Comment (BlopApple) [reply src/main/java/seedu/uninurse/model/person/Patient.java]: Fixed.

**Review by izzahaj — APPROVED** [review]
LGTM
